version: '3'

services:
  combo:
    build: .
    volumes:
      - /app/node_modules
      - /app/packages/core/build
      - /app/packages/core/node_modules
      - /app/packages/core/third_party
      - ./docker-entrypoint.sh:/app/docker-entrypoint.sh
      - ./packages/core/data:/app/packages/core/data
      - ./packages/core/dist:/app/packages/core/dist
      - ./packages/core/include:/app/packages/core/include
      - ./packages/core/lib:/app/packages/core/lib
      - ./packages/core/out:/app/packages/core/out
      - ./packages/core/src:/app/packages/core/src
      - ./packages/core/package.json:/app/packages/core/package.json
      - ./packages/core/Makefile:/app/packages/core/Makefile
      - ./packages/core/tsconfig.json:/app/packages/core/tsconfig.json
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./jest.config.json:/app/jest.config.json
      - ./roms:/app/roms
